extra:
  generator: false # hide the line "Made with Material for MkDocs"

markdown_extensions:
  - tables
  - admonition
  - pymdownx.escapeall
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - mdx_truly_sane_lists

theme:
  name: "material"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/library-shelves
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
